// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1DUA7tIKPthqjaQZVOnsXt2_78yk5lLY',
    appId: '1:851077372449:web:5d3918adc2961537fba160',
    messagingSenderId: '851077372449',
    projectId: 'diabetes-app-59777',
    authDomain: 'diabetes-app-59777.firebaseapp.com',
    storageBucket: 'diabetes-app-59777.firebasestorage.app',
    measurementId: 'G-SMNKHQK693',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8N6b8OGEa01GyAkvDuT1cujMfGURU5yA',
    appId: '1:851077372449:android:8873a399de6960a0fba160',
    messagingSenderId: '851077372449',
    projectId: 'diabetes-app-59777',
    storageBucket: 'diabetes-app-59777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUPiUJGBNixt0fC32e0Yvk1rc9ejBUzg0',
    appId: '1:851077372449:ios:726a50f22c7a8b82fba160',
    messagingSenderId: '851077372449',
    projectId: 'diabetes-app-59777',
    storageBucket: 'diabetes-app-59777.firebasestorage.app',
    iosBundleId: 'com.example.diabetesApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUPiUJGBNixt0fC32e0Yvk1rc9ejBUzg0',
    appId: '1:851077372449:ios:726a50f22c7a8b82fba160',
    messagingSenderId: '851077372449',
    projectId: 'diabetes-app-59777',
    storageBucket: 'diabetes-app-59777.firebasestorage.app',
    iosBundleId: 'com.example.diabetesApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1DUA7tIKPthqjaQZVOnsXt2_78yk5lLY',
    appId: '1:851077372449:web:27248b92c0f05fcffba160',
    messagingSenderId: '851077372449',
    projectId: 'diabetes-app-59777',
    authDomain: 'diabetes-app-59777.firebaseapp.com',
    storageBucket: 'diabetes-app-59777.firebasestorage.app',
    measurementId: 'G-R1Y11T754X',
  );
}
